/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.countdowns;

import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.*;
import org.bukkit.Bukkit;
import org.bukkit.scheduler.BukkitTask;

import java.util.EnumSet;

@Linked
public class EndCountdown extends StateDependent {

    private BukkitTask task;

    public EndCountdown() {
        super(EnumSet.of(FightState.END));
    }

    @Override
    public void enable() {
        if (Config.isEvent()) {
            task = Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), this::stop, 200);
        } else {
            task = Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), this::restart, Config.EndTime);
        }
    }

    private void restart() {
        FightWorld.resetWorld();
        MissileWars.waiting();
    }

    private void stop() {
        //Staggered kick to prevent lobby overloading
        if (Bukkit.getOnlinePlayers().isEmpty()) {
            Bukkit.shutdown();
            return;
        }

        Bukkit.getOnlinePlayers().iterator().next().kickPlayer(null);
        Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), this::stop, 10);
    }

    @Override
    public void disable() {
        if (task != null && !task.isCancelled()) task.cancel();
    }
}
