/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.listener;

import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.Config;
import de.steamwar.misslewars.FightState;
import de.steamwar.misslewars.MissileWars;
import de.steamwar.misslewars.WinReasons;
import org.bukkit.Material;
import org.bukkit.entity.EntityType;
import org.bukkit.event.EventHandler;
import org.bukkit.event.block.BlockPhysicsEvent;
import org.bukkit.event.entity.EntityExplodeEvent;

import java.util.EnumSet;

@Linked
public class PortalDestructListener extends BasicListener {

    public PortalDestructListener() {
        super(EnumSet.of(FightState.FIGHTING));
    }

    @EventHandler
    public void onBlockupdate(BlockPhysicsEvent e) {
        if (e.getBlock().getType() != Material.NETHER_PORTAL) return;
        int z = e.getBlock().getZ();
        if (z == MissileWars.getRedTeam().getPortalZ()) {
            MissileWars.end(WinReasons.PORTAL_DESTROYED, MissileWars.getBlueTeam());
        }
        if (z == MissileWars.getBlueTeam().getPortalZ()) {
            MissileWars.end(WinReasons.PORTAL_DESTROYED, MissileWars.getRedTeam());
        }
    }

    @EventHandler
    public void onExplosion(EntityExplodeEvent e) {
        if (e.getEntityType() != EntityType.FIREBALL) return;

        double z = e.getLocation().getZ();
        double distRed = Math.abs(Config.RedPortalZ + 0.5 - z);
        double distBlue = Math.abs(Config.BluePortalZ + 0.5 - z);
        if (distRed < 2 || distBlue < 2) e.setCancelled(true);
    }
}
