/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import com.comphenix.tinyprotocol.TinyProtocol;
import de.steamwar.linkage.Linked;
import net.minecraft.network.protocol.game.ClientboundLoginPacket;
import net.minecraft.network.protocol.game.CommonPlayerSpawnInfo;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.Level;

@Linked
public class WorldIdentifier {

    private static ResourceKey<Level> resourceKey = null;

    public static void set(String name) {
        resourceKey = new ResourceKey<>(new ResourceLocation("minecraft", "dimension"), new ResourceLocation("steamwar", name));
    }

    public WorldIdentifier() {
        TinyProtocol.instance.addFilter(ClientboundLoginPacket.class, (player, packet) -> {
            if (resourceKey == null) return packet;

            return new ClientboundLoginPacket(packet.playerId(),
                    packet.hardcore(),
                    packet.levels(),
                    packet.maxPlayers(),
                    packet.chunkRadius(),
                    packet.simulationDistance(),
                    packet.reducedDebugInfo(),
                    packet.showDeathScreen(),
                    packet.doLimitedCrafting(),
                    new CommonPlayerSpawnInfo(
                            packet.commonPlayerSpawnInfo().dimensionType(),
                            resourceKey,
                            packet.commonPlayerSpawnInfo().seed(),
                            packet.commonPlayerSpawnInfo().gameType(),
                            packet.commonPlayerSpawnInfo().previousGameType(),
                            packet.commonPlayerSpawnInfo().isDebug(),
                            packet.commonPlayerSpawnInfo().isFlat(),
                            packet.commonPlayerSpawnInfo().lastDeathLocation(),
                            packet.commonPlayerSpawnInfo().portalCooldown(),
                            packet.commonPlayerSpawnInfo().seaLevel()
                    ),
                    packet.enforcesSecureChat()
            );
        });
    }
}
