/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.fightsystem.commands;

import de.steamwar.command.SWCommand;
import de.steamwar.entity.CWireframe;
import de.steamwar.entity.REntityServer;
import de.steamwar.fightsystem.Config;
import de.steamwar.fightsystem.FightSystem;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class TechareaCommand extends SWCommand {
    private final Map<UUID, REntityServer> servers = new HashMap<>();

    public TechareaCommand() {
        super("techarea");

        Bukkit.getScheduler().runTaskTimer(FightSystem.getPlugin(), () -> servers.forEach((uuid, rEntityServer) -> rEntityServer.tick()), 2, 2);
    }

    @Register
    public void genericCommand(Player player) {
        if (servers.containsKey(player.getUniqueId())) {
            servers.get(player.getUniqueId()).close();
        } else {
            REntityServer server = new REntityServer();
            CWireframe wireframe = new CWireframe(server);

            wireframe.setPos1(Config.BlueInsetRegion.getMinLocation(Config.world));
            wireframe.setPos2(Config.BlueInsetRegion.getMaxLocation(Config.world).subtract(1, 1, 1));
            wireframe.setBlock(Material.RED_CONCRETE.createBlockData());

            server.addPlayer(player);
            servers.put(player.getUniqueId(), server);
        }
    }
}
