/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.world;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.config.BauServer;
import de.steamwar.bausystem.region.Region;
import de.steamwar.bausystem.utils.ScoreboardElement;
import de.steamwar.core.CRIUWakeupEvent;
import de.steamwar.data.BauLockState;
import de.steamwar.linkage.Linked;
import de.steamwar.network.packets.PacketHandler;
import de.steamwar.network.packets.server.BaulockUpdatePacket;
import de.steamwar.sql.UserConfig;
import lombok.Getter;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

@Linked
public class BauLockStateScoreboard extends PacketHandler implements ScoreboardElement, Listener {

    private static final String BAU_LOCK_CONFIG_NAME = "baulockstate";

    @Getter
    private BauLockState lockState = loadLockState();

    private BauLockState loadLockState() {
        String state = UserConfig.getConfig(BauServer.getInstance().getOwner(), BAU_LOCK_CONFIG_NAME);
        return state == null ? BauLockState.OPEN : BauLockState.valueOf(state);
    }

    @Handler
    public void handleBaulockUpdatePacket(BaulockUpdatePacket packet) {
        lockState = loadLockState();
    }

    @EventHandler
    public void onCRIUWakeup(CRIUWakeupEvent event) {
        lockState = loadLockState();
    }

    @Override
    public ScoreboardGroup getGroup() {
        return ScoreboardGroup.FOOTER;
    }

    @Override
    public int order() {
        return -10;
    }

    @Override
    public String get(Region region, Player p) {
        if (!BauServer.getInstance().getOwner().equals(p.getUniqueId())) {
            return null;
        }
        switch (lockState) {
            case OPEN:
                return null;
            default:
                return "§e" + BauSystem.MESSAGE.parse("SCOREBOARD_LOCK_" + lockState.name(), p);
        }
    }
}
