/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.lobby.listener;

import de.steamwar.lobby.LobbySystem;
import de.steamwar.lobby.command.ModifyCommand;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerTeleportEvent;

import java.util.function.Function;

public class AlphaWall implements Listener {

    public static float REFLECT_X = 360f;
    public static float REFLECT_Z = 180f;

    private final Function<Location, Boolean> allowed;
    private final float reflect;

    public AlphaWall(Function<Location, Boolean> allowed, float reflect) {
        this.allowed = allowed;
        this.reflect = reflect;
        Bukkit.getPluginManager().registerEvents(this, LobbySystem.getInstance());
    }

    @EventHandler
    public void onMove(PlayerMoveEvent event) {
        Player player = event.getPlayer();
        if (ModifyCommand.modifying(player) || allowed.apply(event.getTo())) return;

        Location to = event.getFrom().clone();
        to.setYaw(reflect - to.getYaw());
        player.teleport(to, PlayerTeleportEvent.TeleportCause.PLUGIN);
    }
}
