/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.towerrun.countdowns;

import de.steamwar.linkage.Linked;
import de.steamwar.towerrun.TowerRun;
import de.steamwar.towerrun.config.Config;
import de.steamwar.towerrun.game.TowerRunGame;
import de.steamwar.towerrun.state.GameStates;
import lombok.Getter;
import lombok.Setter;
import org.bukkit.Bukkit;
import org.bukkit.Sound;

import java.util.EnumSet;

@Getter
@Linked
public class LobbyCountdown extends Countdown {

    @Setter
    private boolean override = false;

    public LobbyCountdown() {
        super(EnumSet.of(GameStates.WAITING));
    }

    @Override
    int defaultTime() {
        return Config.LOBBY_TIMER;
    }

    @Override
    void timerEnd() {
        TowerRunGame.prepareTowerOrStart();
        override = false;
    }

    @Override
    boolean timerShouldCancel() {
        return !override && Bukkit.getOnlinePlayers().size() < Config.MIN_PLAYERS;
    }

    @Override
    void run() {
        TowerRun.getMessage().broadcastActionbar("GAME_STARTING", time);
        if (time < 10) {
            Bukkit.getOnlinePlayers().forEach(player -> player.playSound(player.getLocation(), Sound.BLOCK_NOTE_BLOCK_PLING, 1, 1));
        }
    }

    @Override
    void timerReset() {
        TowerRun.getMessage().broadcastActionbar("GAME_WAITING");
    }
}
