/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils.bossbar;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.region.Region;
import org.bukkit.Bukkit;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarFlag;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerQuitEvent;

public class RegionedBossbar implements BauSystemBossbar, Listener {

    private BossBar bossBar;
    private Region region;
    private Player player;

    public RegionedBossbar(BossBar bossBar, Region region, Player player) {
        this.bossBar = bossBar;
        this.region = region;
        this.player = player;
        Bukkit.getPluginManager().registerEvents(this, BauSystem.getInstance());
    }

    @Override
    public String getTitle() {
        return bossBar.getTitle();
    }

    @Override
    public void setTitle(String title) {
        bossBar.setTitle(title);
    }

    @Override
    public double getProgress() {
        return bossBar.getProgress();
    }

    @Override
    public void setProgress(double progress) {
        bossBar.setProgress(progress);
    }

    @Override
    public BarColor getColor() {
        return bossBar.getColor();
    }

    @Override
    public void setColor(BarColor color) {
        bossBar.setColor(color);
    }

    @Override
    public BarStyle getStyle() {
        return bossBar.getStyle();
    }

    @Override
    public void setStyle(BarStyle style) {
        bossBar.setStyle(style);
    }

    @Override
    public boolean hasFlag(BarFlag flag) {
        return bossBar.hasFlag(flag);
    }

    @Override
    public void addFlag(BarFlag flag) {
        bossBar.addFlag(flag);
    }

    @Override
    public void removeFlag(BarFlag flag) {
        bossBar.removeFlag(flag);
    }

    @Override
    public boolean isVisible() {
        return bossBar.isVisible();
    }

    @Override
    public void setVisible(boolean visible) {
        bossBar.setVisible(visible);
    }

    @Override
    public Region getRegion() {
        return region;
    }

    @EventHandler
    public void onPlayerMove(PlayerMoveEvent event) {
        if (event.getPlayer() != player) return;
        if (region.getArea().inRegion(event.getTo(), false)) {
            bossBar.addPlayer(player);
        } else {
            bossBar.removePlayer(player);
        }
    }

    @EventHandler
    public void onPlayerQuit(PlayerQuitEvent event) {
        if (event.getPlayer() != player) return;
        cleanup();
    }

    @Override
    public void cleanup() {
        if (bossBar != null) {
            bossBar.removeAll();
            bossBar = null;
        }
        region = null;
        player = null;

        PlayerMoveEvent.getHandlerList().unregister(this);
        PlayerQuitEvent.getHandlerList().unregister(this);
    }
}
